# Generated by Django 3.1.6 on 2021-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_auto_20210206_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, upload_to='coverphotos/'),
        ),
    ]
