# Generated by Django 3.1.6 on 2021-02-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0007_auto_20210207_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
