# Generated by Django 3.1.6 on 2021-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0009_auto_20210207_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
