# Generated by Django 3.1.6 on 2021-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0010_auto_20210207_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
